
# netlify.toml

[build]
  # cómo instalar dependencias (opcional)
  install = "npm ci"
  # tu comando de build
  command = "npm run build"
  # carpeta que el plugin-nextjs publica
  publish = ".next"

# Variables de entorno para producción
[context.production.environment]
  # Prisma / Neon
  DATABASE_URL                       = "postgresql://neondb_owner:npg_DBUat0C7vnfz@ep-little-moon-a460redc-pooler.us-east-1.aws.neon.tech/neondb?pgbouncer=true&sslmode=require"

  # NextAuth
  NEXTAUTH_URL                       = "https://bloom-fisio.netlify.app"
  NEXTAUTH_SECRET                    = "TU_SECRETO_DE_32_CARACTERES"

  # Stripe
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = "pk_test_…"
  STRIPE_SECRET                      = "sk_test_…"

  # Si usas otras (Easy-Appointments, etc):
  EA_KEY                             = "tu_api_key_easy_appointments"
  NEXT_PUBLIC_APP_BASE               = "https://bloom-fisio.netlify.app"

# Este bloque va al nivel raíz, ¡no dentro del [context]!
[[plugins]]
  package = "@netlify/plugin-nextjs"

# ¡Clave! Redirige todo /api/* a las funciones que genera el plugin
[[redirects]]
  from       = "/api/*"
  to         = "/.netlify/functions/:splat"
  status     = 200
  force      = true